### ISSUE TITLE
Tomato Sauce tagged as minecraft:water..

### ISSUE THREAD

**Issue by MisterZam27** [DragonsPlusMinecraft/CreateCentralKitchen#103]
### Minecraft Version

1.20.1

### Describe the Bug

So I have a custom shapeless recipe from immersive engineering and one of the tagged fluid is water as input. Surprisingly in the recipe menu it switches from water bucket and tomato sauce bucket. Please fix thanks

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the tomato sauce fluid entry to remove the water tag, which was causing it to be interchangeable with water in recipes.

I also created pull request: https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/pull/104


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by MisterZam27** [comment]
```js
ServerEvents.tags('fluid', event => {
    event.remove('minecraft:water', 'create_central_kitchen:tomato_sauce')
    event.remove('minecraft:water', 'create_central_kitchen:flowing_tomato_sauce')
})
```
