### ISSUE TITLE
No valid recipe provided

### ISSUE THREAD

**Issue by sherlockzym** [DragonsPlusMinecraft/CreateCentralKitchen#11]
Don't know which button to press to confirm the selected recipe, resulting in held cooking guide always showing "No valid recipe provided".

选中食谱后，不知道按什么按钮来确认配方，导致手上的烹饪指南一直显示未指定有效配方

**Comment by RaymondBlaze** [comment]
Just close the interface and the data shall be saved. If this isn't the case, please elaborate how to reproduce the problem, preferably with screenshots.

关掉界面就能自动保存，如果情况不是这样的话请详细描述如何复现，能配上截图就更好了。

**Comment by sherlockzym** [comment]
Sorry, it was my operation being wrong.
At that time I remembered selecting the recipe, handed it to the blaze, the arm took one of the ingredients, rice when I haven't put in other ingredients yet, but the cooking pot is already outputting cooked rice, so I think the recipe did not take effect, and took the cooking guide, the tooltip shows "No valid recipe provided".
I selected the recipe again and got the same tooltip, which caused me a lot of confusion until you replied me that I could use goggles to see the recipe tooltip.
It's probably because the mistake in the first test that led me to misunderstanding, but the train schedule can see my previous settings when removed.
I would very much like to be able to see the recipe tab automatically saved after selecting the recipe when the mouse is pointed.
Translated with www.DeepL.com/Translator (free version), manually fixed.

抱歉，是我操作有误了，因为当时我记得选中了食谱，但是交给烈焰人，动力臂取了其中一种食材是米饭，我还没放别的材料，却在烹饪出米饭，我认为配方没生效，于是我取下烹饪指南，鼠标显示未指定，我再次选定食谱还是告诉我未选定，这对我造成了很大的困惑，直到你答复我发现带上工程师护目镜能看到烈焰人的食谱显示，可能是因为第一次我测试的失误，导致我误解了，不过列车时刻表取下时可以看到我之前的设定，我非常希望能在鼠标指向的时候能看到选择食谱后自动保存的食谱标签

**Comment by RaymondBlaze** [comment]
You can actually open the interface by right-clicking (while sneaking if you're still on 1.1.0), so there's no need to take the guide from the stove. Anyways, it's most likely the real problem is that the guide dropped from stove isn't preserving its content, I feel like this has been fixed in 1.2.0, so I'm gonna close this issue as resolved.

你实际上也可以直接右击烈焰人炉灶（在1.1.0时需要潜行）打开界面，所以实际上是不需要从烈焰人炉灶中取下指南的。不管怎么说，看起来实际的问题是烈焰人炉灶掉落的指南没有保存当中的内容，我感觉这个问题在1.2.0中已经修复了，所以我将以“已解决”的状态关闭这个Issue。
