### ISSUE TITLE
inventory crash

### ISSUE THREAD

**Issue by Uncle-Dirge** [DragonsPlusMinecraft/CreateCentralKitchen#22]
### Minecraft Version

1.19.2

### Describe the Bug

when I open my inventory on a modded server with this mod I get a crash related to liquid tea? 

### Reproduction Steps

1.log in to server
2.open inventory
3.
...

### Expected Result

just a flat crash to launcher 

### Crash Report or Log

https://pastebin.com/qdUFs2Vc

### Mod Version

create_central_kitchen-1.19.2-for-create-0.5.0.i-1.2.2.jar

**Comment by RaymondBlaze** [comment]
1.2.2 added the missing Long Rose Hip Tea fluid according to #21, I feel like this crash is caused by Forge's registry sync, which means the server's version is not 1.2.2, please update the server's mod version or downgrade the client mod version so they match.
Apogolies for not noting this out in changelog ;)
