### ISSUE TITLE
Air in Overweight Farming recipe output

### ISSUE THREAD

**Issue by ChiefArug** [DragonsPlusMinecraft/CreateCentralKitchen#58]
### Minecraft Version

1.19.2

### Describe the Bug

https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/blob/1.19.2/0.5.1-dev/src/generated/resources/datapacks/overweight_farming/data/create_central_kitchen/recipes/emptying/melon_juice.json#L17
There is air in this recipe, which could cause unforseen bugs

### Reproduction Steps

Visit this url: https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/blob/1.19.2/0.5.1-dev/src/generated/resources/datapacks/overweight_farming/data/create_central_kitchen/recipes/emptying/melon_juice.json#L17
Look at the airiness

### Expected Result

Not to have air as a result... Instead just dont include that in the result array

### Other Mods

Not relevant

### Mod Version

Should this field say "incompatibility occurred"? Version is 1.3.8 anyway

### Forge Version

43.2.21

**Comment by MarbleGateKeeper** [comment]
Well that's a bug caused by Overweight Farming itself:
[The code](https://github.com/0rc1nus/Overweight-Farming/blob/3a751954fcf8ae774dd38d60e2da74d2f4458a0b/src/main/java/net/orcinus/overweightfarming/items/MelonJuiceItem.java#L22)
It should override craftRemainder but it doesn't.

I'll do a workaround.
